export const POSTS = [
  {
    _id: "1",
    text: "Started learning by Doing",
    img: "/posts/post1.png",
    user: {
      username: "Palash001",
      profileImg: "/avatars/boy1.png",
      fullName: "Palash tiwari",
    },
    comments: [
      {
        _id: "1",
        text: "Backend girl",
        user: {
          username: "avinasha02",
          profileImg: "/avatars/girl1.png",
          fullName: "avinasha singh",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "john00",
      profileImg: "/avatars/boy2.png",
      fullName: "john marzu",
    },
    comments: [
      {
        _id: "1",
        text: "Backend girl",
        user: {
          username: "avinasha02",
          profileImg: "/avatars/girl1.png",
          fullName: "avinasha singh",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "shivam011",
      profileImg: "/avatars/boy3.png",
      fullName: "shivam saxena",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      username: "harsh",
      profileImg: "/avatars/boy3.png",
      fullName: "harshpo",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "sushmita1",
          profileImg: "/avatars/girl3.png",
          fullName: "sushmita jain",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "palash tiwari",
    username: "palash11",
    profileImg: "/avatars/boy2.png",
  },
  {
    _id: "2",
    fullName: "harsh",
    username: "harsh shrivastava",
    profileImg: "/avatars/girl1.png",
  },
  {
    _id: "3",
    fullName: "shubh jaat",
    username: "shubh99",
    profileImg: "/avatars/boy3.png",
  },
  {
    _id: "4",
    fullName: "Daisy shah",
    username: "daisydoe",
    profileImg: "/avatars/girl2.png",
  },
];
